version: "2"

volumes:
  recordings:

services:
  rpi-audio-guest-book:
    build: .
    restart: always
    tty: true
    labels:
      io.balena.features.dbus: '1'
    privileged: true
    ports:
      - 80:80
    volumes:
        - 'recordings:/recordings'
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/dev/snd:/dev/snd"
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
      INPUT_LISTENER: "gpio"
      RECORDINGS_PATH: "/recordings/"

  wifi-connect:
    build:
      context: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
    environment:
        DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

  supervisor:
    build:
      context: ./supervisor
    restart: always
    network_mode: host
    privileged: true
